name: arewa_dev
description: A new Flutter project.
publish_to: 'none' # Set to 'none' for private projects

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.2.10
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  webview_flutter: ^4.13.0
  flutter_code_editor: ^0.3.4
  highlight: ^0.7.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  # highlight: ^0.7.0
  # webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#000000" # Background color (black)
  image: assets/images/logo.png # Your splash logo
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
